### ISSUE TITLE
OpenSSL_1_1_1n

### ISSUE THREAD

**Issue by LawrE18** [bcrypto/bee2evp#11] opened 2022-03-24 13:35 UTC
Сборка bee2evp c OpenSSL_1_1_1n проходит успешно, но при вызове например команды `openssl engine -c -t bee2evp`
отображается следующая ошибка:

139635733828928:error:2506406A:DSO support routines:dlfcn_bind_func:could not bind to the requested symbol name:../crypto/dso/dso_dlfcn.c:188:symname(**EVP_PKEY_get_base_id**): ../local_OpenSSL_1_1_1n/lib/libbee2evp.so: undefined symbol: **EVP_PKEY_get_base_id**

**Comment by blackbearman** [comment] 2024-01-12 06:47
Not a bug.
Engines for versions 3.0 and 1.1.1 are incompatible. Message is shown during the checking the version that was used for engine compilation. All details are available here: https://github.com/openssl/openssl/issues/17962
Fixed in OpenSSL 1.1.1q and later.

**Closed by blackbearman** 2024-01-12 06:47 UTC
